version: '3.9'

services:
  app:
    image: todo-backend:latest
    container_name: symfony-production
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: "pgsql://postgres:postgres@db:5432/postgres?serverVersion=13&charset=utf8"

  db:
    image: postgres:13
    container_name: symfony-db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
